#!/usr/bin/env python3
"""Regenerate the Claude-side Model Switch page in the Obsidian vault.

Mirrors Codex's obsidian_model_memory.rebuild_model_switches: reads every
ledger record, groups into the same six task categories, and rewrites one
Markdown page with a visible table (Direction/reason column shows
initial/upgrade/downgrade/freeze/no_switch/operational_fallback) plus each
record's full JSON embedded as an HTML comment so the page regenerates
byte-for-byte from itself. Deliberately a SEPARATE file from Codex's own
Skills/Model Switch.md — different model catalog, must never be read by
Codex's own adaptive learner or corrupt its matching.

No vault path is hardcoded (this skill is published publicly and must not
embed any machine-specific personal path). Resolution order:
  1. --vault PATH
  2. $CLAUDE_SKILLS_OBSIDIAN_VAULT environment variable
  3. error, with a message telling the caller to set one of the above.

Usage: python3 sync_vault.py [--vault PATH]
"""

import argparse
import json
import os
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
LEDGER_PATH = SKILL_ROOT / "local" / "ledger.jsonl"
PAGE_RELATIVE = Path("Skills") / "Claude Model Switch.md"


def resolve_vault(cli_value):
    if cli_value:
        return Path(cli_value).expanduser()
    env_value = os.environ.get("CLAUDE_SKILLS_OBSIDIAN_VAULT")
    if env_value:
        return Path(env_value).expanduser()
    raise SystemExit(
        "No vault path given. Pass --vault PATH or set the "
        "CLAUDE_SKILLS_OBSIDIAN_VAULT environment variable to your Obsidian "
        "vault root before running sync_vault.py."
    )

CATEGORIES = (
    ("normal-script-update", "Normal Script Update"),
    ("code-design", "Code Design"),
    ("finding-bugs", "Finding Bugs"),
    ("documentation-instructions", "Documentation and Instructions"),
    ("tests-verification", "Tests and Verification"),
    ("general-work", "General Work"),
)


def load_records():
    if not LEDGER_PATH.exists():
        return []
    records = []
    for line in LEDGER_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records


def task_category(record):
    task_type = (record.get("task_type") or "").lower()
    tokens = set(task_type.replace("-", " ").replace("_", " ").split())
    if tokens & {"doc", "docs", "documentation", "instruction", "instructions", "prompt", "prompts", "readme", "guide"}:
        return "documentation-instructions"
    if tokens & {"test", "tests", "verification", "verify", "validation"}:
        return "tests-verification"
    if tokens & {"bug", "bugs", "debug", "finding", "diagnose", "diagnosis"}:
        return "finding-bugs"
    if tokens & {"design", "architecture", "architect", "plan", "planning"}:
        return "code-design"
    if tokens & {"code", "script", "hook", "hook-auto"}:
        return "normal-script-update"
    return "general-work"


def format_row(record):
    prior = record.get("prior_pair") or "—"
    selected = record.get("pair") or "—"
    effective = selected  # Claude Agent calls have no separate attempt/effective split (single-shot, not receipt-fallback)
    direction = record.get("direction", "")
    reason = record.get("reason", "")
    file_field = record.get("file") or "—"
    tokens = record.get("tokens", "—")
    time_ms = record.get("time_ms", "—")
    status = record.get("status", "")
    row = (
        f"| {record.get('task_type','')} | {record.get('module','') or '—'} | {file_field} "
        f"| {record.get('model','')} / {record.get('effort','')} "
        f"| {prior} / {selected} / {effective} "
        f"| {direction} / {reason} "
        f"| {record.get('record_sha256','')} "
        f"| {tokens} / {time_ms} | {status} |"
    )
    comment = "<!-- claude-model-switch: " + json.dumps(record, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + " -->"
    return row, comment


def build_page(records):
    lines = [
        "# Claude Model Switch",
        "",
        "Claude Code adaptive-model-routing experience ledger, mirrored from the",
        "`auto-model-for-claude` skill's local `local/ledger.jsonl`. Separate page from",
        "Codex's own [[Skills/Model Switch|Model Switch]] — different model catalog",
        "(haiku/sonnet/opus/fable, not gpt-5.x), regenerated by",
        "`~/.claude/skills/auto-model-for-claude/scripts/sync_vault.py`, never read by",
        "any Codex script. Direction vocabulary matches Codex's Model Switch exactly:",
        "`initial`, `upgrade`, `downgrade`, `freeze`, `no_switch`, `operational_fallback`.",
        "",
    ]
    for key, label in CATEGORIES:
        lines += [
            f"## {label}",
            "",
            "| Task type | Module | File | Model | Prior / selected / effective | Direction / reason | Record | Tokens / time | Result |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for record in records:
            if task_category(record) != key:
                continue
            row, comment = format_row(record)
            lines.append(row)
            lines.append(comment)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def sync(vault_path):
    records = load_records()
    page_path = vault_path / PAGE_RELATIVE
    page_path.parent.mkdir(parents=True, exist_ok=True)
    page_path.write_text(build_page(records), encoding="utf-8")
    return {"status": "rebuilt", "records": len(records), "page": str(page_path)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", default=None)
    args = parser.parse_args()
    result = sync(resolve_vault(args.vault))
    json.dump(result, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
